### ISSUE TITLE
you can use mine api as well

### ISSUE THREAD

**Issue by slim-python** [kamronbek29/pinterst_downloader#1]
Hey, just saying...

that you can use my API for downloading Pinterest videos as well,
here is the API [link](https://github.com/slim-python/pinterest-video-downloader-free-api) 
and here is the live demo [https://www.pinterestdownloder.video/](https://www.pinterestdownloder.video/)

**Comment by kamronbek29** [comment]
@slim-python is it free?

**Comment by slim-python** [comment]
Yes dude !!
